trigger:
- main

pool:
  name: Default  # Uses MyAgent01

variables:
  buildConfiguration: 'Release'
  publishFolder: '$(Build.ArtifactStagingDirectory)/publish'

steps:
# 1. Install .NET SDK based on global.json (if present) or project file
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    useGlobalJson: true  # Automatically reads version from global.json if exists

# 2. Authenticate with NuGet feeds
- task: NuGetAuthenticate@1

# 3. Restore NuGet packages
- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: '**/*.csproj'

# 4. Build the solution
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '**/*.csproj'
    arguments: '--configuration $(buildConfiguration)'

# 5. Publish the app
- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    projects: '**/*.csproj'
    arguments: '--configuration $(buildConfiguration) --output $(publishFolder)'

# 6. Deploy to IIS folder
- task: CopyFiles@2
  inputs:
    SourceFolder: '$(publishFolder)'
    Contents: '**'
    TargetFolder: 'C:\inetpub\MyApp'
